# Required to run project under the correct environment.
language: php

# Versions of PHP
php:
  - 5.5.9
  - 5.5
  - 5.6
  - 7.0
  - hhvm

# environment variables
env:
  global:
    - setup=basic

# No Sudo
sudo: false

# Commands
before_script:
  - composer self-update

install:
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --no-interaction --prefer-source; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-source --no-interaction --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-source --no-interaction --prefer-lowest --prefer-stable; fi

# Commands you want to run that will verify your build.
script: vendor/bin/phpunit

# allow_failures: Allow this build to fail under the specified environments.
# fast_finish: If your build fails do not continue trying to build, just stop.
matrix:
  include:
    - php: 5.5.9
      env: setup=stable
  # allow_failures:
  #   - php: 5.6
  #   - php: hhvm
  fast_finish: true

# Customize when the notification emails are sent.
notifications:
    on_success: never
    on_failure: always
