# Required to run project under the correct environment.
language: php

# Versions of PHP
php:
  - 5.5.9
  - 5.5
  - 5.6
  - 7.0
  - hhvm

# environment variables
env:
  global:
    - setup=basic
    - DB=mysql
  # secure:

# No Sudo
sudo: false

## Commands

before_install:
  - composer self-update
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'DROP DATABASE IF EXISTS test;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'create database test;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database IF NOT EXISTS test;'; fi"
  - rvm 1.9.3 do gem install net-ssh -v 2.9.2

install:
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --no-interaction --prefer-source; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-source --no-interaction --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-source --no-interaction --prefer-lowest --prefer-stable; fi

before_script:
  - npm install
  - npm install -g bower phantomjs
  - bower install
  - bundle install
  - php artisan migrate --seed

script:
  - vendor/bin/phpunit
  - npm test
  - bundle install
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

after_success:
  # Capistano WIP
  # - "openssl aes-256-cbc -k $DEPLOY_KEY -in config/enc/deploy_id_rsa_enc_travis -d -a -out config/enc/deploy_id_rsa"
  # - "[[ $TRAVIS_BRANCH = 'master' ]] && bundle exec cap production deploy"

# allow_failures: Allow this build to fail under the specified environments.
# fast_finish: If your build fails do not continue trying to build, just stop.
matrix:
  # include:
  #   - php: 5.5.9
  #     env: setup=lowest
  #   - php: 5.5.9
  #     env: setup=stable
  allow_failures:
    - php: 5.6
    - php: hhvm
  # driver for PostgreSQL currently unsupported by HHVM, requires 3rd party dependency
  exclude:
  - php: hhvm
    env: DB=pgsql
  fast_finish: true

# Customize when the notification emails are sent.
notifications:
    on_success: never
    on_failure: always
